feat: add ip info

diff --git a/dot_aliases b/dot_aliases
--- a/dot_aliases
+++ b/dot_aliases
@@ -4,6 +4,14 @@
 warning_color='\033[0;33m'
 no_color='\033[1;33m'
 
+# jq
+
+## If jq is not installed, tell the user it is a good idea to install jq
+if ! command -v jq &> /dev/null
+then
+    echo -e "${warning_color}jq is not installed, it is a good idea to install it for better experience${no_color}"
+fi
+
 # fzf
 
 ## If fzf is not installed, tell the user it is a good idea to install fzf
@@ -94,3 +102,34 @@ upload() {
 
 alias upload=upload
 alias up=upload
+
+# Ip Info from http://ip-api.com
+
+ipd() {
+    if [ -z "$1" ]; then
+        echo "Error: No IP address provided."
+        echo "Usage: ip <ip address>"
+        return 1
+    fi
+
+    response=$(curl -s "http://ip-api.com/json/$1?fields=66846719")
+
+    echo "================================"
+    echo "IP: $(echo $response | jq -r '.query')"
+    echo "[$(echo $response | jq -r '.reverse')]"
+    echo "--------------------------------"
+    echo "$(echo $response | jq -r '.city') ($(echo $response | jq -r '.country'))"
+    echo "$(echo $response | jq -r '.lat'), $(echo $response | jq -r '.lon')"
+    echo "--------------------------------"
+    echo "ISP: $(echo $response | jq -r '.isp')"
+    echo "AS: $(echo $response | jq -r '.as')"
+
+    echo -n "IP Type: "
+    [ "$(echo $response | jq -r '.mobile')" = "true" ] && echo -n "Mobile "
+    [ "$(echo $response | jq -r '.proxy')" = "true" ] && echo -n "Proxy "
+    [ "$(echo $response | jq -r '.hosting')" = "true" ] && echo -n "Hosting"
+    echo ""
+    echo "================================"
+}
+
+alias ipd=ipd
